title: Configuration
data:
  website_name: 'PT. GARAM TERANG TRANSPORTINDO'
  website_description: |-
    Lodan Center Complex, No. K1 Jl. Lodan Center Pintu II,
    RT13 / RW.02, Kel. Ancol, Kec. Pademangan, Kota Jakarta
    Utara, DKI Jakarta -14430
  website_logo:
    - logo2.jpeg
  website_favicon:
    - favicon.png
  website_email:
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Sales : sales@gttransportindo.com'
        -
          type: hard_break
        -
          type: text
          text: 'Customer Service : cs@gttransportindo.com'
  website_phone: '+6221 38873009'
  website_address: |-
    Lodan Center Complex, No. K1 Jl. Lodan Center Pintu II,
    RT13 / RW.02, Kel. Ancol, Kec. Pademangan, Kota Jakarta
    Utara, DKI Jakarta -14430
  website_quotation:
    - company-profile.pdf
  website_hongkong_title: 'GT Transport ltd (Hongkong)'
  website_hongkong_phone: '+853 6102 7676'
  website_hongkong_email: cs@gttransportindo.com
  website_hongkong_address: |-
    Unit 1603, 16th Floor, The L. Plaza, 367-
    375 Queenâ€™s Road Central, Sheung Wan -
    Hong Kong
  website_wa_image:
    - wa.png
  website_wa_phone: '628881699899'
